# Generated by Django 3.2.3 on 2021-05-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('CAddress', models.CharField(max_length=100)),
                ('CPhoneNumber', models.IntegerField(default=0)),
                ('CID', models.IntegerField(default=0)),
            ],
        ),
    ]
